"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'nu3%v+&_90se&&gu$!gzab*)=*x^c($wr$v-jij9@ebz+w@&-l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []



# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'main',
    'social.apps.django_app.default'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

AUTHENTICATION_BACKENDS = (  
    'social.backends.facebook.FacebookOAuth2',
    'social.backends.google.GoogleOAuth2',
    'social.backends.google.GoogleOAuth2',
    'social.backends.twitter.TwitterOAuth',
    'social.backends.instagram.InstagramOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.request',
                'social.apps.django_app.context_processors.backends',
                'social.apps.django_app.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'music_app',
        'HOST': '127.0.0.1',
        'USER': 'root',
        'PASSWORD': 'root',
        'PORT': '',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_URL = '/media/'  
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  

AUTH_USER_MODEL = 'main.CustomUser'  

#makes a new 
SOCIAL_AUTH_USER_MODEL = 'main.CustomUser'

# SOCIAL_AUTH_LOGIN_REDIRECT_URL = 'http://localhost:8000/complete/instagram/' 
# SOCIAL_AUTH_LOGIN_URL = '/login/'
# SOCIAL_AUTH_INSTAGRAM_REDIRECT_URL = 'http://localhost:8000/complete/instagram/' 

SOCIAL_AUTH_TWITTER_KEY = 'xwQvYHw0vsjBPGBP26kq4QdaQ' 
SOCIAL_AUTH_TWITTER_SECRET = 'cpPZNGA5lFHTT7eu1qf0GaN5miwMCKjcpI6VxGE1NN4rJmpZCh'

SOCIAL_AUTH_FACEBOOK_KEY = '1519072575080235'
SOCIAL_AUTH_FACEBOOK_SECRET = '3d350157c4d8e995dc773fd47f8f07f1'

SOCIAL_AUTH_INSTAGRAM_KEY = 'fe0e17ac91c24522945a3128b42fd412'
SOCIAL_AUTH_INSTAGRAM_SECRET = 'f8ea14cdac5f4c749e3a789201c83934'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '703031032564-38jpk2tlbqjbf5ub7l9jajgr41qfbrjf.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'cM8q0VzDYzjRSfj_9YTsbiej'

#API KEY
FMAKEY = '60BLHNQCAOUFPIBZ'

EMAIL_HOST= 'smtp.gmail.com'
EMAIL_PORT= 587

EMAIL_HOST_USER = 'hendrycksaimee@gmail.com'
EMAIL_HOST_PASSWORD= 'coconuts'
EMAIL_USE_TLS = True
